# This file was generated by ~/.linux_home_config/install.sh and will be overridden by ~/.linux_home_config/update.sh
# To make permanent changes (e. g. in .bashrc), create the file "A.bashrc" in ~/.linux_home_config/persistent/ and run ~/.linux_home_config/update.sh

# ls aliases
# More fancy when using GNU's ls
ls --version 2>/dev/null | grep -q "GNU"
if [ $? -eq 0 ]
then
	alias ll='ls -lAhF --group-directories-first --time-style="+%H:%M %d.%m.%Y"'
else
	alias ll='ls -lAhF'
fi
alias la='ls -A'
alias l='ls -CFx'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Use Vim tabs
alias vim='vim -p'

# Use vimrc.lite in rvim
alias rvi='rvim'
alias rvim='rvim -u ~/.vimrc.lite'
